/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: WillisChiejina (https://sketchfab.com/WillisChiejina)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/audi-rs5-75d636ab26b1423ca61ffd0fd758fd0a
Title: Audi RS5
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'



function Model({ color = '#ffffff', ...props }) {
  const { nodes, materials } = useGLTF('/models/audi_rs5.glb')

  useEffect(() => {
    if (materials.Paint) {
      materials.Paint.map = null
      materials.Paint.color.set(color)
    }
  }, [color, materials])

  return (
    <group {...props} dispose={null}>
      <group scale={0.003} position={[0, 0.111, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_Car_Body_0.geometry}
          material={materials.Car_Body}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_Car_Body_0_1.geometry}
          material={materials.Car_Body}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_Paint_0.geometry}
          material={materials.Paint}
        />
        <group position={[206.932, -82.502, 332.593]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wheel_Painted_Metal_0.geometry}
            material={materials.Painted_Metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wheel_Metal_0.geometry}
            material={materials.Metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wheel_Bolts_Aloy_0.geometry}
            material={materials.Bolts_Aloy}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wheel_Brake_Calipers_0.geometry}
            material={materials.Brake_Calipers}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wheel_Tyre_Emblem_0.geometry}
            material={materials.Tyre_Emblem}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wheel_Tyre_0.geometry}
            material={materials.Tyre}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wheel_Brake_Disc_0.geometry}
            material={materials.Brake_Disc}
          />
        </group>
        <group position={[-206.115, -82.502, 332.593]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wheel002_Painted_Metal_0.geometry}
            material={materials.Painted_Metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wheel002_Metal_0.geometry}
            material={materials.Metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wheel002_Bolts_Aloy_0.geometry}
            material={materials.Bolts_Aloy}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wheel002_Brake_Calipers_0.geometry}
            material={materials.Brake_Calipers}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wheel002_Tyre_Emblem_0.geometry}
            material={materials.Tyre_Emblem}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wheel002_Tyre_0.geometry}
            material={materials.Tyre}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wheel002_Brake_Disc_0.geometry}
            material={materials.Brake_Disc}
          />
        </group>
        <group position={[206.932, -82.502, -308.071]} rotation={[0.95, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wheel001_Painted_Metal_0.geometry}
            material={materials.Painted_Metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wheel001_Metal_0.geometry}
            material={materials.Metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wheel001_Bolts_Aloy_0.geometry}
            material={materials.Bolts_Aloy}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wheel001_Brake_Calipers_0.geometry}
            material={materials.Brake_Calipers}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wheel001_Tyre_Emblem_0.geometry}
            material={materials.Tyre_Emblem}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wheel001_Tyre_0.geometry}
            material={materials.Tyre}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wheel001_Brake_Disc_0.geometry}
            material={materials.Brake_Disc}
          />
        </group>
        <group position={[-206.115, -82.502, -308.071]} rotation={[0.95, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wheel004_Painted_Metal_0.geometry}
            material={materials.Painted_Metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wheel004_Metal_0.geometry}
            material={materials.Metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wheel004_Bolts_Aloy_0.geometry}
            material={materials.Bolts_Aloy}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wheel004_Brake_Calipers_0.geometry}
            material={materials.Brake_Calipers}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wheel004_Tyre_Emblem_0.geometry}
            material={materials.Tyre_Emblem}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wheel004_Tyre_0.geometry}
            material={materials.Tyre}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wheel004_Brake_Disc_0.geometry}
            material={materials.Brake_Disc}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Glass_Glass_0.geometry}
          material={materials.Glass}
        />
      </group>
    </group>
  )
}

export default Model;

useGLTF.preload('/models/audi_rs5.glb')
